{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend.name" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix        
        path: {{ .Values.ingress.path | default "/" }}
        backend:
          service:
            name: {{ include "frontend.name" . }}
            port: 
              number: {{ .Values.config.port | default "8080" }}
{{- end }} 